image: Visual Studio 2017
version: 0.0.{build}
skip_non_tags: true

environment:
  RELEASE_NOTES: notes

# build cache to preserve files/folders between builds
cache:
# preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - packages -> **\packages.config
  
init:
    - git config --global core.autocrlf input
    # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
    - ps: >-
        if ($env:APPVEYOR_REPO_TAG -eq "true")
        {
          Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
        }

branches:
  only:
    -  /v0.*/

clone_folder: c:\BillingProvider
shallow_clone: true

matrix:
    fast_finish: false

platform:
    - Any CPU

configuration:
    - Release

before_build:
    - ps: $env:RELEASE_NOTES = (Get-Content -Raw -Path .\ReleaseNotes.md)
    - nuget restore -verbosity quiet

build:
    verbosity: minimal

assembly_info:
  patch: true
  file: BillingProvider.WinForms\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

artifacts:
  - path: BillingProvider.$(APPVEYOR_REPO_TAG_NAME).0.zip
    name: zip

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME) 
  description: $(RELEASE_NOTES)
  provider: GitHub
  auth_token:
    secure: cxN2nBb9zspwcuAckFj/6KyRjL3qG192nYOawUKdYjauPl8P92GYupmV9YzYdRtf
  artifact: zip
  skip_tags: true
  on:
    branch: master
    appveyor_repo_tag: true
