//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyTitle("BillingProvider 1.0.0.0")]
[assembly: System.Reflection.AssemblyDescription("BillingProvider 1.0.0.0")]
[assembly: System.Reflection.AssemblyCompany("Nikolay Bely")]
[assembly: System.Reflection.AssemblyProduct("BillingProvider")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) Nikolay Bely 2020")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("75A2B281-0EE5-40D0-A491-8EADFCCC609D")]


